var car = 'subaru';
var age = 25;
var city = 'New York';
var fruits = ['apple', 'banana', 'cherry'];
var person = { name: 'John', age: 30 };
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'city'? I predict False.");
console.log(car == 'city');
console.log("Is age == 25? I predict True.");
console.log(age == 25);
console.log("Is age == 29? I predict False.");
console.log(age == 29);
console.log("Is city == 'New York'? I predict True.");
console.log(city == 'New York');
console.log("Is city == 'Islamabad'? I predict False.");
console.log(city == 'Islamabad');
console.log("Is fruits.length == 3? I predict True.");
console.log(fruits.length == 3);
console.log("Is fruits.length == 4? I predict False.");
console.log(fruits.length == 4);
console.log("Is person.name == 'John'? I predict True.");
console.log(person.name == "John");
console.log("Is person.name == 'Ahmed'? I predict False.");
console.log(person.name == 'Ahmed');
